"""追加 50 条新误解到 data/misconceptions.json，总量从 100 扩展到 150。

新增分布：
- 路由协议误解（RIP/OSPF/BGP）：10 条 mc_101~mc_110
- 应用层协议误解（FTP/SMTP/WebSocket）：10 条 mc_111~mc_120
- 网络安全误解（TLS/防火墙/NAT）：10 条 mc_121~mc_130
- IPv6 相关误解：10 条 mc_131~mc_140
- 数据链路层误解（VLAN/STP）：10 条 mc_141~mc_150
"""
import json
from pathlib import Path

fpath = Path("data/misconceptions.json")
data = json.loads(fpath.read_text(encoding="utf-8"))

new_items = [
    # ── 路由协议误解（mc_101 ~ mc_110）────────────────────────────
    {
        "id": "mc_101",
        "knowledge_point": "RIP 路由协议",
        "misconception": "认为 RIP 使用链路状态算法，能掌握全局拓扑",
        "error_type": "algorithm_confusion",
        "correct_answer": "RIP 是距离矢量协议，每个路由器只知道邻居告知的跳数，不了解全局拓扑；OSPF 才是链路状态协议。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_017"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["comparison_table", "follow_up_question"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_102",
        "knowledge_point": "RIP 收敛",
        "misconception": "以为 RIP 的计数到无穷问题在 RIP v2 中已彻底解决",
        "error_type": "version_confusion",
        "correct_answer": "RIP v2 增加了认证和 CIDR 支持，但计数到无穷（Count to Infinity）问题依然存在；仅通过水平分割、毒性逆转等机制缓解。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_017"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_103",
        "knowledge_point": "OSPF 度量",
        "misconception": "认为 OSPF 使用跳数作为度量值",
        "error_type": "metric_confusion",
        "correct_answer": "OSPF 使用带宽（Cost = 参考带宽 / 接口带宽）作为度量值，跳数是 RIP 的度量。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_018"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_104",
        "knowledge_point": "OSPF DR/BDR",
        "misconception": "认为 OSPF 网络中每个路由器都需要与所有其他路由器建立邻接关系",
        "error_type": "flow_omission",
        "correct_answer": "在广播/NBMA网络中，OSPF 选举 DR 和 BDR，非 DR/BDR 路由器只与 DR/BDR 建立完全邻接，减少 LSA 泛洪。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_018"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["simulation", "follow_up_question"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_105",
        "knowledge_point": "BGP 协议类型",
        "misconception": "认为 BGP 是内部网关协议（IGP），用于 AS 内部路由",
        "error_type": "classification_error",
        "correct_answer": "BGP 是外部网关协议（EGP/路径矢量协议），用于不同自治系统（AS）之间的路由交换；OSPF 和 RIP 才是 IGP。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_019"],
        "weak_prerequisites": ["kp_011"],
        "interventions": ["comparison_table", "follow_up_question"],
        "kp_node_ids": ["kp_011"],
    },
    {
        "id": "mc_106",
        "knowledge_point": "BGP 选路",
        "misconception": "认为 BGP 总是选择跳数最少的路由",
        "error_type": "metric_confusion",
        "correct_answer": "BGP 使用多个属性（Weight、Local_Pref、AS_PATH、MED等）综合选路，AS_PATH 最短只是其中一个因素，Weight 和 Local_Pref 优先级更高。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_019"],
        "weak_prerequisites": ["kp_011"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_011"],
    },
    {
        "id": "mc_107",
        "knowledge_point": "OSPF 区域",
        "misconception": "认为 OSPF 所有路由器必须在同一 Area 内才能互通",
        "error_type": "scope_error",
        "correct_answer": "OSPF 支持多区域设计，不同 Area 通过 ABR（区域边界路由器）和 Area 0（骨干区）互通，非骨干区必须连接到 Area 0。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_018"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_108",
        "knowledge_point": "路由协议管理距离",
        "misconception": "认为管理距离（AD）数值越大，路由越可信",
        "error_type": "direction_reversal",
        "correct_answer": "管理距离越小越可信：直连路由 AD=0，静态路由 AD=1，OSPF AD=110，RIP AD=120。AD 大的路由只在没有更小 AD 路由时才被使用。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_017"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_109",
        "knowledge_point": "静态路由 vs 动态路由",
        "misconception": "认为静态路由性能优于动态路由，应在所有场景使用静态路由",
        "error_type": "overgeneralization",
        "correct_answer": "静态路由无法自动响应拓扑变化，适合小规模网络或特定场景；大型网络需要动态路由协议（OSPF/BGP）实现自动收敛。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_017"],
        "weak_prerequisites": ["kp_010"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_010"],
    },
    {
        "id": "mc_110",
        "knowledge_point": "路由环路",
        "misconception": "认为 TTL 字段能完全防止路由环路",
        "error_type": "mechanism_confusion",
        "correct_answer": "TTL 只能限制数据包的最大跳数（避免永久循环），不能阻止路由环路的产生；路由环路需通过水平分割、毒性逆转、路由协议收敛等机制来防止。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_017"],
        "weak_prerequisites": ["kp_009", "kp_010"],
        "interventions": ["simulation", "follow_up_question"],
        "kp_node_ids": ["kp_010"],
    },

    # ── 应用层协议误解（mc_111 ~ mc_120）────────────────────────────
    {
        "id": "mc_111",
        "knowledge_point": "FTP 工作模式",
        "misconception": "认为 FTP 只有一个连接（控制连接），数据和命令在同一通道传输",
        "error_type": "flow_omission",
        "correct_answer": "FTP 使用双通道：控制连接（端口21）传输命令，数据连接（端口20/动态端口）传输文件内容，两者独立工作。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_040"],
        "weak_prerequisites": ["kp_016"],
        "interventions": ["simulation", "follow_up_question"],
        "kp_node_ids": ["kp_016"],
    },
    {
        "id": "mc_112",
        "knowledge_point": "FTP 主动/被动模式",
        "misconception": "认为 FTP 主动模式下，数据连接由客户端发起",
        "error_type": "direction_reversal",
        "correct_answer": "FTP 主动模式下，数据连接由服务器主动连接到客户端指定端口；被动模式下才是客户端发起数据连接。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_040"],
        "weak_prerequisites": ["kp_016"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_016"],
    },
    {
        "id": "mc_113",
        "knowledge_point": "SMTP 协议",
        "misconception": "认为 SMTP 同时负责邮件发送和接收（收件）",
        "error_type": "scope_error",
        "correct_answer": "SMTP 只负责邮件的发送（从客户端到服务器，或服务器间转发）；邮件接收由 POP3（端口110）或 IMAP（端口143）负责。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_041"],
        "weak_prerequisites": ["kp_016"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_016"],
    },
    {
        "id": "mc_114",
        "knowledge_point": "WebSocket 协议",
        "misconception": "认为 WebSocket 是 HTTP 的扩展，每次通信都需要 HTTP 请求",
        "error_type": "mechanism_confusion",
        "correct_answer": "WebSocket 通过 HTTP Upgrade 握手建立连接后，就升级为全双工 TCP 连接，后续通信不再依赖 HTTP 请求/响应模型，开销极低。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_042"],
        "weak_prerequisites": ["kp_015", "kp_013"],
        "interventions": ["simulation", "follow_up_question"],
        "kp_node_ids": ["kp_015"],
    },
    {
        "id": "mc_115",
        "knowledge_point": "HTTP 无状态",
        "misconception": "认为 HTTP 的无状态特性意味着服务器完全无法识别同一用户的连续请求",
        "error_type": "overgeneralization",
        "correct_answer": "HTTP 协议本身无状态，但通过 Cookie/Session/Token 等机制，可以在应用层维护用户状态，使服务器识别同一用户。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_038"],
        "weak_prerequisites": ["kp_015"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_015"],
    },
    {
        "id": "mc_116",
        "knowledge_point": "DNS 查询类型",
        "misconception": "认为 DNS 递归查询和迭代查询结果相同，只是速度不同",
        "error_type": "mechanism_confusion",
        "correct_answer": "递归查询由 DNS 服务器代替客户端完成完整查询过程并返回最终结果；迭代查询每次只返回下一步要查询的服务器地址，由客户端逐步查询。两者的查询负担分配不同。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_039"],
        "weak_prerequisites": ["kp_015"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_015"],
    },
    {
        "id": "mc_117",
        "knowledge_point": "HTTP/2 特性",
        "misconception": "认为 HTTP/2 只是 HTTP/1.1 的加密版本",
        "error_type": "version_confusion",
        "correct_answer": "HTTP/2 的核心改进是二进制帧、多路复用（同一连接并发多个请求/响应）、头部压缩（HPACK）和服务器推送，与加密无直接关系（HTTPS 在 HTTP/1.1 也可用）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_038"],
        "weak_prerequisites": ["kp_015"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_015"],
    },
    {
        "id": "mc_118",
        "knowledge_point": "DHCP 工作过程",
        "misconception": "认为 DHCP 分配 IP 地址时使用 TCP 连接确保可靠性",
        "error_type": "protocol_confusion",
        "correct_answer": "DHCP 使用 UDP（端口 67/68），因为客户端在获取 IP 前没有完整的 IP 配置，无法建立 TCP 连接。DHCP 通过广播或单播 UDP 完成四步握手（Discover/Offer/Request/ACK）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_039"],
        "weak_prerequisites": ["kp_009", "kp_013"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_009"],
    },
    {
        "id": "mc_119",
        "knowledge_point": "HTTPS 加密范围",
        "misconception": "认为 HTTPS 只加密请求体，URL 路径是明文可见的",
        "error_type": "scope_error",
        "correct_answer": "HTTPS（TLS）建立加密通道后，整个 HTTP 报文（包括 URL 路径、请求头、请求体）都被加密，中间人只能看到目标域名（SNI）和 IP，无法看到具体路径和参数。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_043"],
        "weak_prerequisites": ["kp_014", "kp_015"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_014"],
    },
    {
        "id": "mc_120",
        "knowledge_point": "CDN 工作原理",
        "misconception": "认为 CDN 会修改 DNS 权威服务器中的原始记录",
        "error_type": "mechanism_confusion",
        "correct_answer": "CDN 通过将域名 DNS 解析权委派给 CDN 的智能 DNS，由其根据用户位置返回最近节点 IP；原始 DNS 权威记录不被修改。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_039"],
        "weak_prerequisites": ["kp_015"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_015"],
    },

    # ── 网络安全误解（mc_121 ~ mc_130）────────────────────────────
    {
        "id": "mc_121",
        "knowledge_point": "TLS 握手",
        "misconception": "认为 TLS 握手只需要客户端和服务器各发送一次消息即可完成",
        "error_type": "flow_omission",
        "correct_answer": "TLS 1.2 握手需要多个往返（ClientHello、ServerHello/Certificate、ClientKeyExchange、Finished等），TLS 1.3 优化到 1-RTT，但仍需多次消息交换完成密钥协商和认证。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_043"],
        "weak_prerequisites": ["kp_014"],
        "interventions": ["simulation", "follow_up_question"],
        "kp_node_ids": ["kp_014"],
    },
    {
        "id": "mc_122",
        "knowledge_point": "防火墙类型",
        "misconception": "认为包过滤防火墙（Packet Filter）能检测应用层攻击",
        "error_type": "scope_error",
        "correct_answer": "包过滤防火墙工作在网络层/传输层，只检查 IP 地址、端口和协议类型；应用层攻击（如 SQL 注入）需要应用层防火墙（WAF）或下一代防火墙（NGFW）来检测。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_044"],
        "weak_prerequisites": ["kp_019"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_019"],
    },
    {
        "id": "mc_123",
        "knowledge_point": "NAT 与安全",
        "misconception": "认为使用 NAT 后内网主机完全无法被外网访问，可代替防火墙",
        "error_type": "overgeneralization",
        "correct_answer": "NAT 隐藏了内网 IP，使外网主动发起的连接无法直达内网主机（增加了一定安全性），但 NAT 不过滤恶意内容，不能替代防火墙；内网主机主动建立的连接仍可能引入威胁。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_044"],
        "weak_prerequisites": ["kp_019"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_019"],
    },
    {
        "id": "mc_124",
        "knowledge_point": "对称加密 vs 非对称加密",
        "misconception": "认为 HTTPS 全程使用非对称加密（RSA）来加密数据",
        "error_type": "mechanism_confusion",
        "correct_answer": "HTTPS 握手阶段使用非对称加密交换密钥，数据传输阶段使用协商好的对称密钥（如 AES）加密；因为非对称加密计算开销大，不适合大量数据加密。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_043"],
        "weak_prerequisites": ["kp_014"],
        "interventions": ["comparison_table", "follow_up_question"],
        "kp_node_ids": ["kp_014"],
    },
    {
        "id": "mc_125",
        "knowledge_point": "DDoS 防护",
        "misconception": "认为增加服务器带宽是防御 DDoS 的根本解决方案",
        "error_type": "overgeneralization",
        "correct_answer": "DDoS 攻击流量可达数百 Gbps 乃至 Tbps，单纯增加带宽难以抗衡；有效防御需要流量清洗中心（CDN/BGP Anycast）、速率限制、IP 信誉库过滤等综合手段。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_044"],
        "weak_prerequisites": ["kp_019"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_019"],
    },
    {
        "id": "mc_126",
        "knowledge_point": "SSL 证书",
        "misconception": "认为 SSL 证书能防止服务器被黑客入侵",
        "error_type": "scope_error",
        "correct_answer": "SSL/TLS 证书只保证传输过程中的数据加密和身份认证（防止中间人攻击），不能防止服务器本身的漏洞被利用。服务器安全需要代码审计、WAF、定期漏洞扫描等。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_043"],
        "weak_prerequisites": ["kp_014"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_014"],
    },
    {
        "id": "mc_127",
        "knowledge_point": "VPN 加密",
        "misconception": "认为 VPN 使数据传输完全不可被监控",
        "error_type": "overgeneralization",
        "correct_answer": "VPN 加密的是用户到 VPN 服务器之间的流量，VPN 服务器本身仍可看到明文数据，且目标服务器仍能看到请求内容（除非端到端加密）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_044"],
        "weak_prerequisites": ["kp_019"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_019"],
    },
    {
        "id": "mc_128",
        "knowledge_point": "ACL 访问控制",
        "misconception": "认为 ACL 只能基于 IP 地址进行过滤",
        "error_type": "scope_error",
        "correct_answer": "扩展 ACL 可以基于源/目的 IP 地址、协议类型（TCP/UDP/ICMP）、源/目的端口号进行精细过滤；标准 ACL 才只能基于源 IP。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_044"],
        "weak_prerequisites": ["kp_019"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_019"],
    },
    {
        "id": "mc_129",
        "knowledge_point": "IPSec 协议",
        "misconception": "认为 IPSec 只工作在传输层，保护 TCP/UDP 数据",
        "error_type": "layer_confusion",
        "correct_answer": "IPSec 工作在网络层，对整个 IP 数据包进行保护（AH 认证 / ESP 加密），不局限于 TCP/UDP，可以保护任何基于 IP 的流量。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_043"],
        "weak_prerequisites": ["kp_014", "kp_007"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_014"],
    },
    {
        "id": "mc_130",
        "knowledge_point": "端口扫描",
        "misconception": "认为关闭防火墙上的所有端口可以使主机完全不可被探测",
        "error_type": "overgeneralization",
        "correct_answer": "即使所有端口被防火墙丢弃（DROP），主机的 IP 地址仍然可被发现（通过 ICMP ping 或 ACK 扫描）；完全隐身需要同时过滤 ICMP 并使用 DROP 而非 REJECT。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_044"],
        "weak_prerequisites": ["kp_009", "kp_019"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_019"],
    },

    # ── IPv6 相关误解（mc_131 ~ mc_140）────────────────────────────
    {
        "id": "mc_131",
        "knowledge_point": "IPv6 地址空间",
        "misconception": "认为 IPv6 地址耗尽问题只是时间问题，终究会和 IPv4 一样",
        "error_type": "scale_confusion",
        "correct_answer": "IPv6 有 128 位地址空间，共 2^128 ≈ 3.4×10^38 个地址，为地球每粒沙子分配约 6×10^23 个地址，在可预见的未来不存在耗尽问题。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_132",
        "knowledge_point": "IPv6 与 NAT",
        "misconception": "认为 IPv6 仍然需要 NAT 来节约地址",
        "error_type": "overgeneralization",
        "correct_answer": "IPv6 地址充足，设计上每个设备可直接分配全球唯一公共地址，不再需要 NAT；NAT 在 IPv6 中不被推荐（会破坏端到端连接性）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_133",
        "knowledge_point": "IPv6 地址书写",
        "misconception": "认为 IPv6 地址中的 :: 可以在一个地址中出现多次",
        "error_type": "syntax_confusion",
        "correct_answer": ":: 表示一个或多个连续的全零 16 位组，在一个 IPv6 地址中只能出现一次，否则无法确定代表多少个零组。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_134",
        "knowledge_point": "IPv6 ARP 替代",
        "misconception": "认为 IPv6 网络中仍然使用 ARP 协议解析 MAC 地址",
        "error_type": "protocol_confusion",
        "correct_answer": "IPv6 使用邻居发现协议（NDP，基于 ICMPv6）替代了 IPv4 的 ARP，通过 NS（邻居请求）和 NA（邻居通告）消息完成地址解析。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012", "kp_009"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_135",
        "knowledge_point": "IPv6 过渡机制",
        "misconception": "认为 IPv4 到 IPv6 的迁移可以一次性切换，不需要过渡机制",
        "error_type": "scope_error",
        "correct_answer": "IPv4 和 IPv6 长期共存，需要过渡机制：双栈（设备同时支持两者）、隧道（将 IPv6 封装在 IPv4 中传输）、NAT64/DNS64（IPv6 访问 IPv4 服务）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_136",
        "knowledge_point": "IPv6 首部",
        "misconception": "认为 IPv6 头部比 IPv4 头部更复杂、更大",
        "error_type": "direction_reversal",
        "correct_answer": "IPv6 基本头部固定为 40 字节，比 IPv4 的可变长头部（20-60字节）更简洁；IPv6 将可选信息移到扩展头部，简化了路由器处理逻辑。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_137",
        "knowledge_point": "IPv6 分片",
        "misconception": "认为 IPv6 路由器会像 IPv4 一样对数据包进行分片",
        "error_type": "mechanism_confusion",
        "correct_answer": "IPv6 中路由器不进行分片，分片只由源端主机负责；路由器使用 ICMPv6 'Packet Too Big' 消息通知源端降低 MTU（路径 MTU 发现）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["comparison_table", "follow_up_question"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_138",
        "knowledge_point": "link-local 地址",
        "misconception": "认为 IPv6 fe80::/10 链路本地地址可以跨路由器路由",
        "error_type": "scope_error",
        "correct_answer": "fe80::/10 是链路本地地址，仅在单个链路（子网）内有效，路由器不会转发此类地址；跨网络通信需要使用全球单播地址（GUA）。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_139",
        "knowledge_point": "SLAAC 地址配置",
        "misconception": "认为 IPv6 无状态地址自动配置（SLAAC）需要 DHCPv6 服务器",
        "error_type": "mechanism_confusion",
        "correct_answer": "SLAAC 不需要 DHCPv6；主机通过监听路由器通告（RA，ICMPv6 Type 134）获得前缀，结合 EUI-64 或随机算法生成接口 ID，完全自主配置地址。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_012"],
    },
    {
        "id": "mc_140",
        "knowledge_point": "IPv6 组播",
        "misconception": "认为 IPv6 保留了广播地址用于一对多通信",
        "error_type": "protocol_confusion",
        "correct_answer": "IPv6 取消了广播，改用组播（Multicast，ff00::/8）和任播（Anycast）；邻居发现等功能通过特定组播地址（如 ff02::1 全节点组播）实现。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_020"],
        "weak_prerequisites": ["kp_012"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_012"],
    },

    # ── 数据链路层误解（VLAN/STP）（mc_141 ~ mc_150）──────────────────
    {
        "id": "mc_141",
        "knowledge_point": "VLAN 间路由",
        "misconception": "认为同 VLAN 的不同子网主机可以直接二层通信",
        "error_type": "layer_confusion",
        "correct_answer": "VLAN 是二层隔离边界，同 VLAN 内可以二层通信；但不同 IP 子网（即使在同 VLAN）的主机需要三层路由才能通信。VLAN 和子网通常一一对应，但并非绝对。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_011"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_006"],
    },
    {
        "id": "mc_142",
        "knowledge_point": "Trunk 端口",
        "misconception": "认为 Trunk 端口只传输一个 VLAN 的流量",
        "error_type": "scope_error",
        "correct_answer": "Trunk 端口（802.1Q）可以同时承载多个 VLAN 的流量，通过在帧中插入 VLAN 标签（4字节）来区分不同 VLAN；Access 端口才只属于一个 VLAN。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_011"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_006"],
    },
    {
        "id": "mc_143",
        "knowledge_point": "STP 根桥选举",
        "misconception": "认为 STP 根桥是网络中性能最强的交换机",
        "error_type": "mechanism_confusion",
        "correct_answer": "STP 根桥由 Bridge ID（优先级+MAC 地址）决定，优先级最低的交换机成为根桥；若优先级相同，则 MAC 地址最小的成为根桥。与性能无关。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_012"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_006"],
    },
    {
        "id": "mc_144",
        "knowledge_point": "STP 端口状态",
        "misconception": "认为 STP 中所有非根端口都处于阻塞状态",
        "error_type": "overgeneralization",
        "correct_answer": "STP 中，每个非根交换机选出一个根端口（Root Port）处于转发状态；每个网段选出一个指定端口（Designated Port）转发；只有其余端口才被阻塞（Blocking）以打破环路。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_012"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_006"],
    },
    {
        "id": "mc_145",
        "knowledge_point": "VLAN 标签",
        "misconception": "认为 VLAN ID 可以使用 0 或 4095",
        "error_type": "range_error",
        "correct_answer": "802.1Q VLAN ID 范围是 0-4095（12位），但 0 和 4095 是保留值，实际可用范围是 1-4094；VLAN 1 是默认 VLAN，各厂商通常不允许删除。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_011"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_006"],
    },
    {
        "id": "mc_146",
        "knowledge_point": "交换机 MAC 学习",
        "misconception": "认为交换机转发未知目的 MAC 的帧时会丢弃",
        "error_type": "direction_reversal",
        "correct_answer": "交换机收到目的 MAC 不在 MAC 地址表中的帧时，会进行洪泛（Flooding）：将帧转发到除入端口外的所有端口；只有找到目的 MAC 后才单播转发。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_009"],
        "weak_prerequisites": ["kp_005"],
        "interventions": ["simulation"],
        "kp_node_ids": ["kp_005"],
    },
    {
        "id": "mc_147",
        "knowledge_point": "以太网帧结构",
        "misconception": "认为以太网帧的 FCS 字段用来纠错",
        "error_type": "mechanism_confusion",
        "correct_answer": "FCS（帧校验序列）使用 CRC-32 进行差错检测，只能检测出错误帧并将其丢弃，不能纠正错误；纠错需要更高层协议（如 TCP）的重传机制。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_009"],
        "weak_prerequisites": ["kp_005"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_005"],
    },
    {
        "id": "mc_148",
        "knowledge_point": "半双工与全双工",
        "misconception": "认为现代以太网交换机仍然使用 CSMA/CD 进行碰撞检测",
        "error_type": "technology_outdated",
        "correct_answer": "现代以太网交换机工作在全双工模式，每个端口独享带宽，收发互不干扰，不存在碰撞，因此不需要 CSMA/CD；CSMA/CD 只在早期共享介质（集线器）网络中使用。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_009"],
        "weak_prerequisites": ["kp_005"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_005"],
    },
    {
        "id": "mc_149",
        "knowledge_point": "RSTP 与 STP",
        "misconception": "认为 RSTP（快速生成树）和 STP 的收敛时间相同",
        "error_type": "version_confusion",
        "correct_answer": "STP 收敛时间约 30-50 秒（Listening 15秒 + Learning 15秒）；RSTP 通过 P/A 机制快速协商端口状态，收敛时间通常在 1 秒以内。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_012"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["comparison_table"],
        "kp_node_ids": ["kp_006"],
    },
    {
        "id": "mc_150",
        "knowledge_point": "Private VLAN",
        "misconception": "认为同一 VLAN 内的主机一定能直接二层通信",
        "error_type": "overgeneralization",
        "correct_answer": "私有 VLAN（Private VLAN/Port Isolation）技术允许在同一 VLAN 内隔离端口，使同 VLAN 的主机无法直接通信（如酒店/运营商场景）；通过配置隔离端口实现二层隔离。",
        "chapter": "computer_networking",
        "knowledge_node_ids": ["acu_011"],
        "weak_prerequisites": ["kp_006"],
        "interventions": ["follow_up_question"],
        "kp_node_ids": ["kp_006"],
    },
]

# 追加到现有列表
data.extend(new_items)

fpath.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
print(f"Done! Total misconceptions: {len(data)}")
